### ISSUE TITLE
dubious inference on pigeonhole?

### ISSUE THREAD

**Issue by c-cube** [marijnheule/microsat#10]
Hi,

I've modified slightly microsat to print DRAT proofs (see [temporary branch](https://github.com/c-cube/microsat/tree/issue-hole10); I simply log all learned clauses and an empty clause upon finding "unsat"). However, it seems like the proofs so produced do not always check. On the problem committed on the repo, `hole10.cnf` (a pigeonhole instance), here's the issue:

```
$ gcc -O2 microsat.c -o microsat; ./microsat hole10.cnf 
s UNSATISFIABLE
c statistics of hole10.cnf: mem: 2691474 conflicts: 215592 max_lemmas: 82700

$ drat-trim hole10.cnf proof.drat 
c parsing input formula with 110 variables and 561 clauses
c finished parsing
c conflict claimed, but not detected

s NOT VERIFIED
c verification time: 6.779 seconds

$ drat-trim hole10.cnf proof.drat -f
c parsing input formula with 110 variables and 561 clauses
c finished parsing
c start forward verification
c WARNING: RAT check on proof pivot failed : [8234] 81 0
c RAT check failed on all possible pivots
c failed at proof line 3556 (modulo deletion errors)

s NOT VERIFIED
c verification time: 6.795 seconds
```

**Comment by marijnheule** [comment]
You should change 
fprintf(S->proof, "%d ", in[i]);
to 
fprintf(S->proof, "%d ", clause[i]);

**Comment by c-cube** [comment]
Oh, is there aliasing? My bad, I didn't realize. It works with the change.
