### ISSUE TITLE
invalid result

### ISSUE THREAD

**Issue by c-cube** [marijnheule/microsat#3]
On the given problem, microsat returns
```
s UNSATISFIABLE
c statistics of benchs/sat/ssa4.cnf: mem: 130921 conflicts: 0 max_lemmas: 2000
```
but the problem is solved as satisfiable by other solvers (minisat, picosat, z3)
[should_be_sat.cnf.gz](https://github.com/marijnheule/microsat/files/3632651/should_be_sat.cnf.gz)

**Comment by arminbiere** [comment]
It is a parser issue.  My delta debuggers could not shrink it.  So I did it manually.
This is the smallest counter example I found.  It has todo with comment parsing I think.
I will have a look ...

$ cat > bug.cnf
c p cnf 1 1
p cnf 0 0
microsat bug.cnf 
s UNSATISFIABLE
c statistics of bug.cnf: mem: 21 conflicts: 0 max_lemmas: 2000
$ cadical -n -q bug.cnf
s SATISFIABLE

**Comment by arminbiere** [comment]
It is about comments parsing, before the header ...

I fixed it on my fork

git@github.com:arminbiere/microsat.git


Armin

**Comment by c-cube** [comment]
Thank you Armin, this works! :100:

**Comment by marijnheule** [comment]
I dealt with the comments issue by using Armin's fix.
